org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1

minecraft_version_range=[1.21.1, 1.22)

# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.170
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.0,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


mod_id=pixelmonlevelcap

mod_name=Pixelmonlevelcap

mod_license=All-Rights-Reserved

mod_version=1.0

mod_group_id=de.scorezy

mod_authors=

mod_description=
