modLoader="javafml"
loaderVersion="[36,)"
license="All-Rights-Reserved"

[[mods]]
modId="pixelmonlevelcapsystem"
version="1.0"
displayName="pixelmonlevelcapsystem"
authors="Jxstn/Scorezy"

[[dependencies."pixelmonlevelcapsystem"]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies."pixelmonlevelcapsystem"]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies."pixelmonlevelcapsystem"]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,9.1.13,)"
ordering="NONE"
side="BOTH"