modLoader="javafml"
loaderVersion="[48,)"
license="All-Rights-Reserved"

[[mods]]
modId="pixelmonlevelcapsystem"
version="2.0.2"
displayName="pixelmonlevelcapsystem"
authors="Jxstn/Scorezy"

[[dependencies."pixelmonlevelcapsystem"]]
modId="forge"
mandatory=true
versionRange="[48,)"
ordering="NONE"
side="BOTH"

[[dependencies."pixelmonlevelcapsystem"]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2,)"
ordering="NONE"
side="BOTH"

[[dependencies."pixelmonlevelcapsystem"]]
modId="pixelmon"
mandatory=true
versionRange="[9.2.10,)"
ordering="NONE"
side="BOTH"